namespace DbBroker.Compatibility;

/// <summary>
/// Compares two descriptors for compatibility.
/// </summary>
public class DescriptorComparer
{
    // TODO: Implement comparison logic for descriptors: One from the classes generated by the DbBroker tool and another from the database schema.
}
