//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBBroker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DBBroker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The informed namespace &apos;{0}&apos; was not found in the application context. .
        /// </summary>
        internal static string AssemblyNotFound {
            get {
                return ResourceManager.GetString("AssemblyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A corresponding ConnectionString was not found to the namespace &apos;{0}&apos;. .
        /// </summary>
        internal static string DBBrokerConfigConnStrNotFound {
            get {
                return ResourceManager.GetString("DBBrokerConfigConnStrNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As database option, you need to inform &apos;SQLServer&apos; or &apos;MySQL&apos; (MySQL not fully supported)..
        /// </summary>
        internal static string DBBrokerConfigDatabaseOption {
            get {
                return ResourceManager.GetString("DBBrokerConfigDatabaseOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;DBBroker.config&apos; is already encrypted..
        /// </summary>
        internal static string DBBrokerConfigFileAlreadyEncripted {
            get {
                return ResourceManager.GetString("DBBrokerConfigFileAlreadyEncripted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every line of the DBBroker.config file must have the format: &apos;My.Namespace|{SQLServer or MySQL}|ConnectionString&apos;. .
        /// </summary>
        internal static string DBBrokerConfigFileFormat {
            get {
                return ResourceManager.GetString("DBBrokerConfigFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DBBroker.config configuration file was not found in &apos;{0}&apos;. .
        /// </summary>
        internal static string DBBrokerConfigFileNotFound {
            get {
                return ResourceManager.GetString("DBBrokerConfigFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please inform lines of the configuration file as elements of the array. Array null or empty..
        /// </summary>
        internal static string DBBrokerConfigInfoIncomplete {
            get {
                return ResourceManager.GetString("DBBrokerConfigInfoIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  /* Generated as a courtesy without warranty by DBBroker */
        /// /* ==================================================== */
        /// /* Why not paying a coffee for us at www.getdbbroker.com? */
        /// /* We need your help to keep moving. */
        /// /* Donations via PayPal - quick and safe ;) */
        /// /* Creation: {0} */
        ///
        /// /* [!]
        ///   - REMEMBER TO CREATE OR SET THE PROPER DATABASE CONTEXT BEFORE YOU RUN THIS SCRIPT;
        ///   - REVISE THIS SCRIPT;
        /// */.
        /// </summary>
        internal static string DBBrokerScriptMessage {
            get {
                return ResourceManager.GetString("DBBrokerScriptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of the encrypted DBBroker.config file is invalid. Make sure you are using the same password used to create it (Configuration.EncryptionPassword)..
        /// </summary>
        internal static string EncryptionPasswordInvalid {
            get {
                return ResourceManager.GetString("EncryptionPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The encryption password in property &apos;Configuration.EncryptionPassword&apos; cannot be null or shorter than 6 characters when working with encrypted DBBroker.config file..
        /// </summary>
        internal static string EncryptionPasswordNull {
            get {
                return ResourceManager.GetString("EncryptionPasswordNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; needs to be of type &apos;System.Collections.Generic.List&apos;..
        /// </summary>
        internal static string ErrorBadList {
            get {
                return ResourceManager.GetString("ErrorBadList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DBBroker.config file has does not have the line &apos;{0}&apos;. It has &apos;{1}&apos; line(s)..
        /// </summary>
        internal static string ErrorConfigFileHasNoSuchLine {
            get {
                return ResourceManager.GetString("ErrorConfigFileHasNoSuchLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration context cannot be null..
        /// </summary>
        internal static string ErrorConfigurationContextRequired {
            get {
                return ResourceManager.GetString("ErrorConfigurationContextRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The execution of the SQL script failed. {0} SQL: &apos;{1}&apos;. (That message is restrict to debugging).
        /// </summary>
        internal static string ErrorExecutingSqlCommand {
            get {
                return ResourceManager.GetString("ErrorExecutingSqlCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value found in {0} to &apos;Id&apos; property is invalid integer. .
        /// </summary>
        internal static string ErrorIdValueNotValid {
            get {
                return ResourceManager.GetString("ErrorIdValueNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please inform the corresponding table and primary key to the class &apos;{0}&apos; using the [DBMappedClass] attribute in this class. .
        /// </summary>
        internal static string ErrorIncompleteMap {
            get {
                return ResourceManager.GetString("ErrorIncompleteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail during the load of property &apos;{0}.{1}&apos;. {2}. .
        /// </summary>
        internal static string ErrorLoadingProp {
            get {
                return ResourceManager.GetString("ErrorLoadingProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, verifique os valores do atributo [DBMappedList] na propriedade &apos;{0}.{1}&apos;.  Há algo errado..
        /// </summary>
        internal static string ErrorMappedListCheckMapping {
            get {
                return ResourceManager.GetString("ErrorMappedListCheckMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please inform all properties of the attribute [DBMappedList] of &apos;{0}.{1}&apos;..
        /// </summary>
        internal static string ErrorMappedListInfo {
            get {
                return ResourceManager.GetString("ErrorMappedListInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}.{1}&apos; must be of type &apos;System.Collections.Generic.List&apos; .
        /// </summary>
        internal static string ErrorMappedListUsage {
            get {
                return ResourceManager.GetString("ErrorMappedListUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops... Something went wrong during a try of recovering data. .
        /// </summary>
        internal static string ErrorMessageDefault {
            get {
                return ResourceManager.GetString("ErrorMessageDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every mapped class need a &apos;Id&apos; integer property. The class &apos;{0}&apos; does not have it. .
        /// </summary>
        internal static string ErrorMissingIdProp {
            get {
                return ResourceManager.GetString("ErrorMissingIdProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wow... DBBroker does not allow multiple databases mechanisms (SQLServer and MySQL) in the same context. That would be a mess..
        /// </summary>
        internal static string ErrorMultipleDatabases {
            get {
                return ResourceManager.GetString("ErrorMultipleDatabases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The namespace &apos;{0}&apos; appears more than once in DBBroker.config file..
        /// </summary>
        internal static string ErrorNamespaceAlreadyInformed {
            get {
                return ResourceManager.GetString("ErrorNamespaceAlreadyInformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The namespace &apos;{0}&apos; was not specified in the file DBBroker.config.
        /// </summary>
        internal static string ErrorNamespaceNotFound {
            get {
                return ResourceManager.GetString("ErrorNamespaceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while saving the data to &apos;{0}&apos;. .
        /// </summary>
        internal static string ErrorSavingObject {
            get {
                return ResourceManager.GetString("ErrorSavingObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is more than one mapped namespaces. Please use the ScriptGenerator constructor where you can specify a namespace. .
        /// </summary>
        internal static string ErrorScriptMultipleNamespacesMapped {
            get {
                return ResourceManager.GetString("ErrorScriptMultipleNamespacesMapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction specified has an invalid connection. .
        /// </summary>
        internal static string ErrorTranAssociatedConnectionNull {
            get {
                return ResourceManager.GetString("ErrorTranAssociatedConnectionNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was not possible to connect to the database. .
        /// </summary>
        internal static string ErrorUnableToConnect {
            get {
                return ResourceManager.GetString("ErrorUnableToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal unexpected error. [581].
        /// </summary>
        internal static string ErrorUnexpectedNullProp {
            get {
                return ResourceManager.GetString("ErrorUnexpectedNullProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is more than one assembly in context with the namespace &apos;{0}&apos;. .
        /// </summary>
        internal static string MultipleAssembliesWithSameNamespace {
            get {
                return ResourceManager.GetString("MultipleAssembliesWithSameNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The column name cannot be null or empty. .
        /// </summary>
        internal static string NullOrEmptyColumnName {
            get {
                return ResourceManager.GetString("NullOrEmptyColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unnamed.
        /// </summary>
        internal static string Unnamed {
            get {
                return ResourceManager.GetString("Unnamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: The property &apos;{0}&apos; was not mapped. Type not convertible: {1}.
        /// </summary>
        internal static string WarningPropertyNotMapped {
            get {
                return ResourceManager.GetString("WarningPropertyNotMapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure you commit the external transaction informed..
        /// </summary>
        internal static string WarningTransactionNotCommited {
            get {
                return ResourceManager.GetString("WarningTransactionNotCommited", resourceCulture);
            }
        }
    }
}
